variable "project_domain" {
  type        = string
  description = <<-EOT
    The project domain. An fqdn, eg. "test.example.com".
  EOT
}
variable "zone" {
  type        = string
  description = <<-EOT
    The zone within the domain.
    eg. if the domain is "test.example.com", then this should be "example.com"
  EOT
}
variable "project_cert_name" {
  type        = string
  description = <<-EOT
    The project's cert name
  EOT
  default     = ""
}
variable "project_cert_key_id" {
  type        = string
  description = <<-EOT
    The key name to retrieve the project's cert's private key from AWS
  EOT
  default     = ""
}
variable "path" {
  type        = string
  description = <<-EOT
    The path where we will place the terraform config to deploy.
  EOT
  default     = ""
}
variable "cert_manager_version" {
  type        = string
  description = <<-EOT
    The version of cert manager to install.
  EOT
  default     = "v1.13.1"
}
variable "configure_cert_manager" {
  type        = bool
  description = <<-EOT
    Whether or not to configure cert manager with AWS access keys.
    If left false, we will use the certificate generated by Terraform with the cluster.
  EOT
  default     = false
}
