name: Update Go Dependencies

on:
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Mondays at 00:00
  workflow_dispatch: # Allow manual triggering

jobs:
  update-deps:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Update Script
        run: |
          chmod +x ./update-go-deps.sh
          ./update-go-deps.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(deps): update go dependencies in test module"
          title: "chore(deps): update go dependencies in test module"
          body: "Automated PR to update Go dependencies in the `test` module."
          branch: "auto-update-go-deps"
          delete-branch: true
