name: Update Go Dependencies

on:
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Mondays at 00:00
  workflow_dispatch: # Allow manual triggering

permissions: {}

jobs:
  update-deps:
    name: 'Update Deps'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        id: checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Update Script
        id: run-update-script
        run: bash .github/workflows/scripts/nix-run.sh "bash .github/workflows/scripts/update-go-deps.sh"

      - name: Create Pull Request
        id: create-pull-request
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = await import(`${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/create-update-deps-pr.js`);
            await script.default({ github, context, core, process });
